apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-15T19:11:21Z"
  labels:
    app: ip-addr
  name: ip-addr-service
  namespace: default
  resourceVersion: "1345"
  selfLink: /api/v1/namespaces/default/services/ip-addr-service
  uid: f3972e3d-5026-11ea-9467-42010a80017e
spec:
  clusterIP: 10.12.11.93
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-to-8080-tcp
    nodePort: 30856
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: 443-to-8080-tcp
    nodePort: 31539
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: ip-addr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
