apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-16T17:59:35Z"
  labels:
    app: ip-addr
  name: ip-addr-service
  namespace: default
  resourceVersion: "2439"
  selfLink: /api/v1/namespaces/default/services/ip-addr-service
  uid: 175689a1-50e6-11ea-9df2-42010a800155
spec:
  clusterIP: 10.0.5.210
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-to-3000-tcp
    nodePort: 30239
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: 443-to-3000-tcp
    nodePort: 31344
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: ip-addr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
